version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloom_db
    environment:
      POSTGRES_USER: bloom
      POSTGRES_PASSWORD: bloom
      POSTGRES_DB: bloom
    ports: ["5433:5432"]
    volumes: [ "dbdata:/var/lib/postgresql/data" ]
volumes: { dbdata: {} }
